version: "3.9"

services:
    db:
        image: lambdaiith/iith-dashboard-backend-db:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=p123
            - POSTGRES_DB=dashboard
    web:
        image: lambdaiith/iith-dashboard-backend-web:latest
        ports: 
            - "8000:8000"
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASS: p123
            POSTGRES_DB: dashboard
        depends_on:
            - db
        restart: on-failure:10
    caddy:
        image: caddy:latest
        restart: unless-stopped
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - web
        restart: on-failure:10

volumes:
    postgres_data:
