version: "3.9"

services:
    db:
        image: postgres:12-alpine
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=p123
            - POSTGRES_DB=dashboard
    web:
        build: .
        ports: 
            - "8000:8000"
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASS: p123
            POSTGRES_DB: dashboard
        depends_on:
            - db

volumes:
    postgres_data:
