name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
            ref: master
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.db
          push: true
          tags: lambdaiith/iith-dashboard-backend-db:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: lambdaiith/iith-dashboard-backend-web:latest
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./academic-curriculum-script/Dockerfile
          push: true
          tags: lambdaiith/iith-dashboard-backend-script:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: copy file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          overwrite: true
          source: "docker-compose.yml,Caddyfile,static"
          target: "compose"
      -
        name: create=json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with: 
          name: "credentials1.json"
          json: ${{ secrets.CREDENTIALS_JSON }}
          dir: 'compose/'
      - 
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
              whoami
              cd compose
              docker-compose up -d --force-recreate
